#docker-compose up -d
#docker-compose down
#version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: java_user
      POSTGRES_PASSWORD: java_password
      POSTGRES_DB: java_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U java_user -d java_db" ]
      interval: 5s
      timeout: 5s
      retries: 5


